# Generated by Django 3.1.12 on 2024-12-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_link', models.URLField()),
                ('image_link', models.URLField()),
                ('price', models.DecimalField(blank=True, db_column='Price (Dollar)', decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('price_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating_out_of_5', models.FloatField(blank=True, null=True)),
                ('number_of_ratings', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('available_colors', models.TextField(blank=True, null=True)),
                ('storage_gb', models.IntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=5)),
            ],
            options={
                'db_table': 'demiMarktBirlesik',
            },
        ),
    ]
