# Generated by Django 3.1.12 on 2024-12-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_link', models.URLField()),
                ('image_link', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('price_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating_out_of_5', models.FloatField(blank=True, null=True)),
                ('number_of_ratings', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('CPU', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
