# Generated by Django 3.1.12 on 2024-12-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20241227_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_column='Price (Dollar)', decimal_places=2, max_digits=10, null=True),
        ),
    ]
